import '@storybook/addon-actions/register';
import '@storybook/addon-links/register';
import '@storybook/addon-knobs/register'
import '@storybook/addon-console';
import '@storybook/addon-viewport/register'
import 'storybook-readme/register';
import 'storybook-addon-intl/register';
import 'storybook-chrome-screenshot/register';
import 'storybook-addon-specifications/register';
